# Generated by Django 3.0.4 on 2020-03-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards', '0002_pagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_datetime', models.DateTimeField(auto_now=True)),
                ('finish_datetime', models.DateTimeField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboards.Dashboard')),
            ],
        ),
    ]
