# Generated by Django 3.0.4 on 2020-03-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0001_squashed_0005_auto_20200318_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
